version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=reagent_portal
      - POSTGRES_PASSWORD=reagent_portal
      - POSTGRES_DB=reagent_portal_dev
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: